'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace FullStackedBar2DChart.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As FullStackedBar2DChart.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New FullStackedBar2DChart.Properties.Settings())), FullStackedBar2DChart.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return FullStackedBar2DChart.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
